services:
  customerService:
    image: maven:3.9.6-eclipse-temurin-21
    ports:
      - 4444:8080
    volumes:
      - .:/customer-service
    working_dir: /customer-service
    entrypoint: mvn -pl customer-service spring-boot:run
  kycService:
    image: maven:3.9.6-eclipse-temurin-21
    ports:
      - 5555:8080
    volumes:
      - .:/kyc-service
    working_dir: /kyc-service
    entrypoint: mvn -pl kyc-service spring-boot:run


